name: Inclusive Organization
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: your-organization-name
          team: your-team-name
          comment: Single or multiline comment
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
